- name: default value
  hosts: localhost
  become: no 
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "{{Course | default('Ansible')}} is big"

- name: lower
  hosts: localhost
  vars:
    greetings: "GM friend ramesh"
  become: no 
  tasks:
  - name: lower value
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"   

- name: upper
  hosts: localhost
  vars:
    greetings: "Hello good morning"
  become: no
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"        