- name: default value
  hosts: localhost
  become: no 
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "{{Course | default('Ansible')}} is big"

- name: lower
  hosts: localhost
  vars:
    greetings: "GM friend ramesh"
  become: no 
  tasks:
  - name: lower value
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"   

- name: upper
  hosts: localhost
  vars:
    greetings: "Hello good morning"
  become: no
  tasks:
  - name: upper
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"       

- name: unique
  hosts: localhost
  vars:
    numbers: [1,2,4,5,3,2,5,6,7,7,8]
  become: no
  tasks:
  - name: unique
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"         

- name: min max
  hosts: localhost
  vars:
    numbers: [35,45,3,46,78,12,23,34]
  become: no 
  tasks:
  - name: min max
    ansible.builtin.debug:
      msg: "Min: {{numbers | min}}, Max: {{numbers | max}}"  

- name: dict2items
  hosts: localhost
  become: no
  vars:
    my_dict:
      Course: "Devops"
      Trainer: "Siva"
      Duration: "120 hours"
  tasks:      
  - name: dict2items
    ansible.builtin.debug:
      msg: "before::::{{my_dict}}"



  - name: dict2items
    ansible.builtin.debug:
      msg: "Dict items after {{my_dict | dict2items }}"    